dist: bionic
language: minimal

jobs:
  include:
    - arch: ppc64le
      env: BUILD_DOCKER=1
      docker: true
    - arch: amd64
      env: BUILD_DOCKER=1
      docker: true
    - env: BUILD_TYPE=Release
    - env: BUILD_TYPE=Debug

before_script:
  - ci/install_deps.sh || travis_terminate 1;

script:
  - ci/build.sh || travis_terminate 1;
